### ISSUE TITLE
A few non-fex functions are missing

### ISSUE THREAD

**Issue by AliAskari** [johnyf/nfsim#1]
I have searched for the following function on fex and your other repos but I didn't find them.
- [`create_quadrics`](https://github.com/johnyf/nfsim/blob/aed6d7a5995f4b9cb58d4ff3b01dffafdc6a57d3/navigation_function/khatib/khatib_testing_obstacles.m#L7)

- [`beta_quadrics`](https://github.com/johnyf/nfsim/blob/aed6d7a5995f4b9cb58d4ff3b01dffafdc6a57d3/navigation_function/khatib/test_khatib.m#L33)

I tried to write my own version of `create_quadrics` but it's not working as expected.

**Comment by johnyf** [comment]
Thank you for spotting these, fixed as of 0f28c8ef4847af2964e20038040956900bacd455. It was introduced by renaming these files to [create_ellipsoids](https://github.com/johnyf/nfsim/commit/61a66e8134747a769ee67b461372f0704cadb392#diff-2528c25d87228b31ff526e708ef8a311) and [`beta_ellispoids.m`](https://github.com/johnyf/nfsim/commit/ecaa8f09002bd0a424717e25541e1adf1670bc2e#diff-3fffd96f51ba0d3f14c2784ba5ea5490).
